apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-customers
  labels:
    app: app-customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-customers
  template:
    metadata:
      labels:
        app: app-customers
    spec:
      containers:
        - name: app-customers
          image: emil2245/app-customers-micronaut:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "k8s"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            # Configura tu base de datos
            - name: DATASOURCES_DEFAULT_URL
              value: "jdbc:postgresql://postgres-service:5432/customers_db"
            - name: DATASOURCES_DEFAULT_USERNAME
              value: "postgres"
            - name: DATASOURCES_DEFAULT_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5



#----------------
apiVersion: v1
kind: Service
metadata:
  name: app-customers-service
  labels:
    app: app-customers
spec:
  type: ClusterIP
  selector:
    app: app-customers
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http