global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['proxy:8080']

  - job_name: 'consul'
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['consul:8500']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgresql-exporter:9187']
     
  - job_name: 'helidon-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['authors:8080', 'books:8080']

  - job_name: 'micronaut-services'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['customers:8080', 'recommend:8080']

  - job_name: 'frontend-vaadin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-web-vaadin:8080']